# Author: Alex Liu
# Last modified: 2019-12-27
# Description: This scripts determines the number of a's in the first n letters of an infinitely repeated string

# Setup -------------------------------------------------------------------

remove(list = ls())

library(dplyr)
library(stringr)

options(scipen = 999)

dir <- "/Users/ahtlau/Library/Mobile Documents/com~apple~CloudDocs/Data/HackerRank/Repeated String"

setwd(dir)

# Analysis ----------------------------------------------------------------

count_a <- function (file) {
  
  # Load data
  (raw <- readLines(file.path("input", file), warn = F))
  
  # Extract the string and n, the first n letters of the infinitely repeated string
  # n is also the cutoff point truncating the infinitely repeated string
  (string <- raw[1] %>% str_trim())
  (n <- raw[2] %>% str_trim() %>% as.double()) 
  # as.double is used because as.integer cannot handle a number greater than 2,147,483,647
  # In one of the test cases n is 1,000,000,000,000. It would fail if as.double is not used
  
  # The truncated string might sometimes contain extra bit that is only part of the given string
  # e.g. aba, cutoff is 6, there is no extra bit
  # e.g. aba, cutoff is 4, the extra bit is a
  
  # Methodology: count the number of a's in a given string and multiply it by the number of entire repeats
  # plus the number of a's in the partially repeated string generated by the cutoff point. 
  # The sum is the number of a's in the first n letters of an infinitely repeated string
  
  # Count the number of a in a given string 
  (n_a_in_string <- str_count(string, "a"))
  # Count the number of repeats in the truncated string. Partial repeat is ignored.
  (n_repeats_integer <- floor(n/nchar(string)))
  # Multiply a's by the number of repeats
  (n_a_whole <- n_a_in_string * n_repeats_integer)
  # Test if there are any partial repeat. Remainder is the length of the partially repeated string
  (extra_bit <- n %% nchar(string))
  
  # If there is no extra bit, no further action
  if (extra_bit == 0) {
    (n_a <- n_a_whole)
    # If there is extra bit, count the number of a
  } else {
    # Repeat string one more time and then split per the remainder
    (n_a_in_extra_bit <- rep(string, 1) %>% 
      str_sub(1, extra_bit) %>% 
      str_count("a"))
    # Count total number of a's
    (n_a <- n_a_whole + n_a_in_extra_bit)
  }
}

count_a(file = "input00.txt")
count_a(file = "input01.txt")
count_a(file = "input02.txt")
count_a(file = "input03.txt")
count_a(file = "input04.txt")

